### ISSUE TITLE
Semana 12 - Cliente no puede conectarse a servidor local

### ISSUE THREAD

**Issue by LudwigUC** [IIC2233/Syllabus-2023-1#422]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Hola!! estaba intentando correr el código servidor y cliente TCP que se encuentra en código base, y al intentar correr **el cliente nunca logra establecer la conexión**, pese a que el servidor se ejecuta correctamente y queda en modo "listening", el cliente lanza un error de tipo TimeoutError.
He intentado correr el cliente desde otra ventana de la cmd o desde vscode, pero de todos modos no funciona

**Comment by Hernan4444** [comment]
Hola @LudwigUC 

Viendo el código base, puede ser que `socket.gethostname()` no esté entregando el string esperado en tu pc, y esto provoca que el servidor no se levante correctamente y el cliente tampoco se conecte a donde corresponde.

¿Puedes intentar cambiar `socket.gethostname()` por `"localhost"` en ambos archivos?

 Quedamos atentos,
Saludosヾ(＾-＾)ノ

**Comment by LudwigUC** [comment]
Ahora si funciona, muchas gracias!
¿Existe alguna explicación de por qué sucede esto?

**Comment by Hernan4444** [comment]
Hola @LudwigUC 

Lo que pasa es que `socket.gethostname()` retorna el nombre del computador que ejecuta el código. Y cuando uno hace `socket.bind((socket.gethostname(), PORT))`, dependiendo del sistema operativo, utilizar el nombre puede ser válido o no. 

Por ejemplo, probando el código en mi windows con `socket.gethostname()` funcionó bien, esto implica que la versión de windows que tengo acepta usar el nombre del computador como forma de hacer `bind` en un socket, pero en mac hice lo mismo y el código se caía diciendo:

```python
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Esto significa que en mi versión de mac, justamente usar el nombre del pc no funciona. No obstante, `"localhost"` es una forma estandar de referirse al computador de uno. Por este motivo, sin importar el sistema operativo que se usa, `"localhost"` servirá para indicar utilizar en el socket. Tanto para `bind` como para `connect`.

Gracias a tu consulta, nos logramos percatar de esta situación para corregirlo en los contenidos para los siguientes semestres. ¡Muchas gracias 😄!

Saludosヾ(＾-＾)ノ
